title: Neutrino's ArXiv
show_downloads: False
desciption: 'University of Cambridge
theme: jekyll-theme-minimal

navigation:
- {title: "About", url: "https://jennyjiang478.github.io/vx.github.io/"}
- {title: "Nerdy", url: "https://jennyjiang478.github.io/vx.github.io/"}
- {title: "Blog", url: "https://jennyjiang478.github.io/vx.github.io/"}

plugins: 
- jekyll-feed
